### PR TITLE
Fix RuboCop lint offences

### PR DESCRIPTION
**Pull request by Koronen**
~~There's currently one rule left, `Lint/RescueException`, that needs more thought.~~

Ready for review.

### CODE REVIEW

**Comment by swanson** [comment]
Those exceptions could be scope to whatever Feedjira can create; but I'm not aware of a great way to get that list.

**Comment by swanson** [comment]
:+1: thanks for tackling that :)

**Comment by Koronen** [comment]
Thanks for the hint! I'll have a look next time I have a chance to work on this.

**Comment by swanson** [comment]
Let's merge for now with the inline exceptions -- I can live with those :)

**Comment by Koronen** [comment]
* Removed the unused `finder` parameter in c190d3c0bff7a297363a4dea4f5ca34adc4b8172
* Fixed Lint/RescueException in 0ae414410d7072bcbae6524c81efff7d31279fe8.

  This was done by rescuing `StandardError` instead of `Exception`, which should still cover most if not all errors raised by the Curb and Feedjira libraries. We no longer try to rescue fatal errors, like `NoMemoryError`, which is what RuboCop was complaining about.

  An even better fix for this could be to rescue an even narrower set of errors, but I'll leave that until the next time.

**Comment by swanson** [comment]
Thanks!

**Pull request merged**
