### PR TITLE
Upgrade ruby version to newest supported by Heroku

### PR DESCRIPTION
**Pull request by cyplo**
Heroku-18 does not support `ruby 2.3.3` anymore.
I took this opportunity to upgrade the Ruby version and dependencies.
Deploys happily to Heroku now, all tests pass.
I am however, quite unfamilliar with Ruby ecosystem so may have missed something.
Let me know if this helps :)

p.s. love this product and use it every day :)

### CODE REVIEW

**Comment by cyplo** [comment]
There is a rubocop error - any suggestions on how would you like to have this fixed ?
```
Error: obsolete parameter MaxLineLength (for Style/IfUnlessModifier) found in .rubocop.yml
`Style/IfUnlessModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
obsolete parameter MaxLineLength (for Style/WhileUntilModifier) found in .rubocop.yml
`Style/WhileUntilModifier: MaxLineLength` has been removed. Use `Metrics/LineLength: Max` instead
``` ?

**Comment by Koronen** [comment]
Hi @cyplo! Thank you for your contribution. 👍 

I think it would be good if you could extract most of the changes made to `Gemfile.lock` from this branch (apart from the new Ruby version) and into a set of smaller Pull Requests where we upgrade a few dependencies at a time. That should make each PR easier to manage, and should hopefully mean that we don't have to deal with that RuboCop error in this PR.

> p.s. love this product and use it every day :)

Thank you! That's nice to hear. 🙂

**Comment by cyplo** [comment]
good idea, will do :)

**Comment by cyplo** [comment]
Done, @Koronen - this PR is just the ruby version changes now. :)
CI seems to not be super happy with `phantom` tests though - is this a known issue ? If not - I could take a look into that later.

**Comment by Koronen** [comment]
Applying the following patch should fix the `mocha-phantomjs` build step.

```diff
diff --git a/Gemfile b/Gemfile
index 95557cd..f1f7da3 100644
--- a/Gemfile
+++ b/Gemfile
@@ -26,7 +26,7 @@ end
 
 gem "activerecord", "~> 4.2.6"
 gem "bcrypt", "~> 3.1"
-gem "delayed_job", "~> 4.1"
+gem "delayed_job", "~> 4.1", ">= 4.1.4"
 gem "delayed_job_active_record", "~> 4.1"
 gem "feedbag", "~> 0.9.5"
 gem "feedjira", "~> 2.1.3"
diff --git a/Gemfile.lock b/Gemfile.lock
index 4f9a82a..25c575f 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -40,8 +40,8 @@ GEM
       tins (~> 1.6.0)
     crass (1.0.3)
     debugger-linecache (1.2.0)
-    delayed_job (4.1.1)
-      activesupport (>= 3.0, < 5.0)
+    delayed_job (4.1.5)
+      activesupport (>= 3.0, < 5.3)
     delayed_job_active_record (4.1.0)
       activerecord (>= 3.0, < 5)
       delayed_job (>= 3.0, < 5)
@@ -185,7 +185,7 @@ DEPENDENCIES
   bcrypt (~> 3.1)
   capybara (~> 2.6)
   coveralls (~> 0.7)
-  delayed_job (~> 4.1)
+  delayed_job (~> 4.1, >= 4.1.4)
   delayed_job_active_record (~> 4.1)
   faker (~> 1.2)
   feedbag (~> 0.9.5)
```

See https://github.com/collectiveidea/delayed_job/blob/v4.1.5/CHANGELOG.md#414---2017-12-29.

With `delayed_job` v4.1.1:

```
$ bundle exec rake -T
/home/koronen/.asdf/installs/ruby/2.5.3/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
rake aborted!
NoMethodError: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
/home/koronen/Code/stringer/Rakefile:8:in `require'
/home/koronen/Code/stringer/Rakefile:8:in `<top (required)>'
/home/koronen/.asdf/installs/ruby/2.5.3/bin/bundle:23:in `load'
/home/koronen/.asdf/installs/ruby/2.5.3/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

**Comment by Koronen** [comment]
For reference:

> Here are our supported Ruby versions:
> 
> **MRI:**
> 
> * `2.3.8` : patchlevel 459, Rubygems : `2.5.2.3` (2.3 is not available on Heroku-18)

https://devcenter.heroku.com/articles/ruby-support#supported-runtimes

**Comment by tsayen** [comment]
Hi all, I wonder if I could help with this. Would fixing the build be enough for this PR to go forward?

**Comment by Koronen** [comment]
I think so, yes. Fixing the build would be much appreciated!

**Comment by cyplo** [comment]
Hi @tsayen - have you had any time to look into this one maybe ? :)

**Comment by tsayen** [comment]
Hi guys, I finally did manage to look into it. 
It looks like the build is fine now, with ruby bumped to 2.6.5 (current stable)
Please take a look at #500

**Comment by cyplo** [comment]
Nice ! - Should I close this one (#496) in favour of #500  ?

**Comment by swanson** [comment]
Closed via #500

**Pull request closed without merging**
