### PR TITLE
Ruby 2.2 fixes

### PR DESCRIPTION
**Pull request by jeroenj**
Updates some dependencies which are required for ruby 2.2.0. I've tested all of them on ruby 2.0.0 and 2.1.5 to make sure they don't break on those rubies.

This will make https://github.com/swanson/stringer/issues/364 easier. :)

### CODE REVIEW

**Comment by Koronen** [comment]
LGTM! :+1:

**Comment by swanson** [comment]
I'm setting aside some time in the next week or so to review/test this. Thanks @jeroenj!

**Comment by Koronen** [comment]
My instance of Stringer has been running smoothly with these changes applied for a couple of hours now. Merging.

**Comment by jeroenj** [comment]
Great. :) I've been running it on 2.2.0 since then without any issues.

**Pull request merged**
