### PR TITLE
Fill feed URL field from params

### PR DESCRIPTION
**Pull request by Koronen**
Read the feed URL from params on request to `/feeds/new` and let it fill the feed URL field. This enables integration with the [RSS Subscription Extension][rss-subscription-ext] extension for Google Chrome and should allow integration with similar extensions, for Google Chrome or other browsers.

[rss-subscription-ext]: https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd

### CODE REVIEW

**Comment by swanson** [comment]
What do you think about a different endpoint? Just so it's clear how this could be used `/feeds/oneclick` or something?

**Comment by swanson** [comment]
Looks like a neat extension - does it open the page in Stringer and we have to click 'Add'? Or is the intent that we can subscribe directly from the `GET`?

**Comment by Koronen** [comment]
When using the extension to subscribe to a feed, it opens the feed reader in a new tab. Feeds and corresponding URLs are configurable, but only `GET`-requests appear to be supported.

My first thought was to add a new endpoint to add the feed directly, without user interaction. Then I changed my mind and implemented it this way because it's the minimal functional patch and let's us avoid using `GET` requests to modify application state.

**Comment by swanson** [comment]
:+1: works for me

**Pull request merged**
