### PR TITLE
Making fonts self hosted #399

### PR DESCRIPTION
**Pull request by mario-areias**
As discussed in #399 it would be good to have fonts hosted instead to go to an external server to download it. Both `Lato` and `Reenie Beanie` are open source and allow this, since they use the OFL license.

### CODE REVIEW

**Comment by mario-areias** [comment]
@swanson have you seen this?

**Comment by swanson** [comment]
Apologies, looks fine -- I want to pull it down locally and test. Will try to get to it by the end of the week.

**Comment by mario-areias** [comment]
Great :) 

Thanks!

**Comment by Koronen** [comment]
Some relevant links:
* Lato Regular licensing information on Typekit: https://typekit.com/eulas/00000000000000000001522c
* Reenie Beanie Regular licensing information on Typekit: https://typekit.com/eulas/00000000000000000000e039
* OFL license: http://scripts.sil.org/OFL

---

> 2) Original or Modified Versions of the Font Software may be bundled, redistributed and/or sold with any software, provided that **each copy contains the above copyright notice and this license**. These can be included either as stand-alone text files, human-readable headers or in the appropriate machine-readable metadata fields within text or binary files as long as those fields can be easily viewed by the user.

Maybe include an appropriate `LICENSE` file in each font folder (`app/public/fonts/lato/` and `app/public/fonts/reenie-beanie/`)?

Apart from that, LGTM! :+1:

**Comment by swanson** [comment]
I'm getting the following warnings on Chrome:

```shell
Failed to decode downloaded font: http://reader.mdswanson.com/fonts/reenie-beanie/ReenieBeanie.woff
tutorial:1 
OTS parsing error: invalid version tag
```

when loading the tutorial page.

**Comment by swanson** [comment]
I've added font attribution to the README -- I think that is sufficient.

@mario-areias Thanks for this PR, sorry for the delay :)

**Comment by mario-areias** [comment]
Great @swanson. Thanks for fixing the ReenieBeanie font! :)

**Pull request merged**
