### PR TITLE
Rubocop and code formatting

### PR DESCRIPTION
**Pull request by jeroenj**
I've generated a `rubocop_todo.yml` and a `rubocop.yml`. This currently fixes only spacing related offences.

If I find the time and there is interest I might look into fixing some other offences.

### CODE REVIEW

**Comment by Koronen** [comment]
LGTM! :+1: I'm all for adding a style guide to this project. @swanson?

**Comment by swanson** [comment]
:+1: to adding it. But I'd rather fix the outstanding issues before merging it in with a ton of exceptions :)

I think this repo is low volume enough that it should be doable.

@jeroenj I'm curious if there is a baseline style guide that these rules are based on? I don't have strong opinions but would prefer one with some existing community buy-in.

**Comment by Koronen** [comment]
RubyCop's default configuration is based on the community-driven "The Ruby Style Guide", https://github.com/bbatsov/ruby-style-guide/.

**Comment by Koronen** [comment]
> But I'd rather fix the outstanding issues before merging it in with a ton of exceptions :)

While I would also prefer to have all the warnings fixed now, I can imagine that taking quite some time and effort. I'm open to the option of merging this PR as-is and fixing the warnings in a series of smaller PRs, which I think could be easier for the author(s) to write and for the reviewer(s) to review.

**Comment by jeroenj** [comment]
Yes, I'd merge it as it is right now too. Since all the exceptions are in a todo file it's quite clear that they're pending. I've also added the project to [RefactorCop](http://www.refactorcop.com/swanson/stringer) so it might attract other people willing to contribute.

I generally try to use the default config as much as possible. I noticed that some of the code has different styling so having separate pull requests might for some changes might be easier to open the discussion.

I'm willing to go through all of them (I already did it several times for other projects) but it might take some time to get it done. :-)

**Comment by swanson** [comment]
I don't have a strong opinion, so merge away :) 

Can we add style check to the build job?

**Comment by Koronen** [comment]
> Can we add style check to the build job?

Yes, please. :smiley:  Do we want to do it in a separate PR or in this one. I'm fine with either.

**Comment by jeroenj** [comment]
Yes, I'll look into it. But not right now. 😃 (it's getting late in CET 😄)

**Comment by jeroenj** [comment]
@swanson I've added it to the build config. The build will fail if rubocop detects offences.

I noticed that ruby 2.1 and 2.2 builds are allowed to fail? Shouldn't we remove that requirement? If one of those would fail it would not be noticed, right?

**Comment by swanson** [comment]
@jeroenj yeah, that's fine if you want to change that

**Comment by jeroenj** [comment]
@swanson I've changed the build setup to not allow failures on 2.1 and 2.2.

If all looks good to you guys this might be merged. I don't think that I'll have the time to go through the other offences in the next few days. By merging there might be a (slight? 🙂) chance that somebody else starts working on it.

**Comment by Koronen** [comment]
LGTM! :+1:

**Pull request merged**
